//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lexer.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About author.
        /// </summary>
        internal static string About_author {
            get {
                return ResourceManager.GetString("About_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  About program.
        /// </summary>
        internal static string About_program {
            get {
                return ResourceManager.GetString("About_program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dima Kovalenko.
        /// </summary>
        internal static string author_name {
            get {
                return ResourceManager.GetString("author_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Automata.
        /// </summary>
        internal static string automata_tab {
            get {
                return ResourceManager.GetString("automata_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        internal static string convert {
            get {
                return ResourceManager.GetString("convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeXer.
        /// </summary>
        internal static string course_project {
            get {
                return ResourceManager.GetString("course_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Field is empty. Please, enter expression.
        /// </summary>
        internal static string Empty_error {
            get {
                return ResourceManager.GetString("Empty_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter expression!.
        /// </summary>
        internal static string Enter_expression_error {
            get {
                return ResourceManager.GetString("Enter_expression_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Evaluate expression.
        /// </summary>
        internal static string Evaluate_polish {
            get {
                return ResourceManager.GetString("Evaluate_polish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Enter your expression here:.
        /// </summary>
        internal static string Expression_label {
            get {
                return ResourceManager.GetString("Expression_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Float:.
        /// </summary>
        internal static string float_t {
            get {
                return ResourceManager.GetString("float_t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grammars.
        /// </summary>
        internal static string grammar_tab {
            get {
                return ResourceManager.GetString("grammar_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Information.
        /// </summary>
        internal static string information {
            get {
                return ResourceManager.GetString("information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        internal static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Integer:.
        /// </summary>
        internal static string int_t {
            get {
                return ResourceManager.GetString("int_t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The expression is incorrect..
        /// </summary>
        internal static string invalid_expr {
            get {
                return ResourceManager.GetString("invalid_expr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Analyze.
        /// </summary>
        internal static string Lexical_analyze_button {
            get {
                return ResourceManager.GetString("Lexical_analyze_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lexical analysis.
        /// </summary>
        internal static string lexical_tab {
            get {
                return ResourceManager.GetString("lexical_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Operation:.
        /// </summary>
        internal static string op {
            get {
                return ResourceManager.GetString("op", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Parans:.
        /// </summary>
        internal static string parans {
            get {
                return ResourceManager.GetString("parans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish notation.
        /// </summary>
        internal static string polish_tab {
            get {
                return ResourceManager.GetString("polish_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Postfix notation.
        /// </summary>
        internal static string Postfix_notation {
            get {
                return ResourceManager.GetString("Postfix_notation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix notation:.
        /// </summary>
        internal static string Prefix_notation {
            get {
                return ResourceManager.GetString("Prefix_notation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Show grammar tree.
        /// </summary>
        internal static string show_grammar_tree {
            get {
                return ResourceManager.GetString("show_grammar_tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Show syntax tree.
        /// </summary>
        internal static string show_sytntax_tree {
            get {
                return ResourceManager.GetString("show_sytntax_tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax analysis.
        /// </summary>
        internal static string syntax_tab {
            get {
                return ResourceManager.GetString("syntax_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        internal static string ukrainian {
            get {
                return ResourceManager.GetString("ukrainian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unary_error Unary operations are not permitted.
        /// </summary>
        internal static string unary_error {
            get {
                return ResourceManager.GetString("unary_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The expression is correct..
        /// </summary>
        internal static string valid_expr {
            get {
                return ResourceManager.GetString("valid_expr", resourceCulture);
            }
        }
    }
}
